spring.application.name=notification-service
server.port=8082

# Database Connection (Creating a separate DB for this microservice)
spring.datasource.url=jdbc:mysql://localhost:3306/bloodbank_notifications?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#  email here
spring.mail.username=vinudanadissa10.email@gmail.com
# Use password
spring.mail.password=1234567891234567
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true